### ISSUE TITLE
Ents defending uruk hai, and other flaws in the ally system

### ISSUE THREAD

**Issue by mgl512** [minetest-LOTR/Lord-of-the-Test#103]
~~Although I killed a lot of them in Mirkwood biomes, the death counter remains at 0 for "lottmobs:spider"~~

~~This is what I have on the mobs deaths in 'lottachievements.txt':
`_[31] = {["balrog"] = 1, ["orc"] = 166, ["elf"] = 0, ["witch_king"] = 0, ["spider"] = 0, ["dunlending"] = 121, ["ithilien_ranger"] = 2, ["ent"] = 1, ["uruk_hai"] = 42, ["raiding_orc"] = 167}`~~

I also noticed that if you (human) fight the uruk_hai that spawn at night in Fangorn biomes, Ents who witness that wil defend them.

**Comment by lumidify** [comment]
Sorry it took me so long to address this issue.
The "Spider Hunter" achievement should work now, but the bug with Ents will probably not be fixed for a while due to a design flaw in the ally system which makes the Ents always defend NPCs, no matter what side they are on. I could make a temporary fix, but it would probably cause other issues so it would be best to wait until I redesign the system itself.

**Comment by Amaz1** [comment]
Mobs will probably be significantly reworked in the rewrite, and this (hopefully!) won't be an issue then - although I'm sure there'll be a lot of other issues to sort out...!
