### ISSUE TITLE
LOTT development architecture overhaul

### ISSUE THREAD

**Issue by Anth0rx** [minetest-LOTR/Lord-of-the-Test#111]
#### I think of an architecture like this:
- Use the `minetest_game` as a base (and make necessary changes in a fork)
- Keep the development of LOTT-mods (and forks of other used mods) inside separate repositories in the minetest-LOTR organization.
- Merge the mods into the `minetest_game` based main repo

This would increase the maintainability of individual mods, make them accessible to others and we could enable CI to keep the mods and base up to date automatically.

This is just a brief summary of my idea regarding the overall development architecture of LOTT.

What do you think about this?

**Comment by Anth0rx** [comment]
Also recently I came across the [repo](https://source.android.com/source/using-repo) tool. Actually it has been developed for Android development but you can use it in general to manage multiple git repos in one directory structure. This is quite handy since the different repos keep independent and you can use it to build more complex projects (like Android or a Minetest subgame with a base and multiple mods).

**Comment by fishyWET** [comment]
The architecture of the subgame has been discussed multiple times.
But using minetest_game is as a base is a no.

The similarity that exists currently is due to LOTT originating as a modpack.
There are no future plans to depend LOTT on minetest_game, rather the plan is to salvage whatever we can and unite LOTT under a completely different, unique structure and reduce dependency on minetest_game completely.
@Amaz1 is currently working on this.

I understand that most subgames refers to a collection of external mods.
And LOTT is currently somewhat proving that.
However, this will not happen in the near future, rather we plan to reduce dependency on external mods nearly completely, due to the fact it is much easier to maintain your own code than others.
And as LOTT grows, we need to start developing our own code anyways, because external apis can no longer sustain what we want.
So your second pointer will become redundant very soon.

So in general, no, they are a couple of great suggestions, but it really doesn't correspond with the goals we have in mind.

**Comment by Anth0rx** [comment]
Thanks for the comprehensive answer. But isn't it much harder to rewrite everything despite there may be some great mods which need just a little bit of tweaking?

**Comment by fishyWET** [comment]
> But isn't it much harder to rewrite everything despite there may be some great mods which need just a little bit of tweaking?

Yes and no.
In the short term, yes.
In the long term, no. The rewrite will provide a better base to expand on.

> Even if we planned to maintain all the codebase ourselves I think we should strive for modularity to make individual LOTT mods available to others to use and modify.

Separating everything into their separate repos actually make things harder, if not as hard to maintain.
The rewrite @Amaz1 is working on, has a focus on modularity too, that will really make the structure much less confusing. I feel that this would be enough to "make individual LOTT mods available to others to use and modify."

> base

LOTT itself has not true "base"
If anything, the entire thing is a base, each and every mod will be as dependent on each other and important.

**Comment by Anth0rx** [comment]
Okay, I understand. Is the code @Amaz1 is working on available publicly?

**Comment by Amaz1** [comment]
> Is the code @Amaz1 is working on available publicly?

Not yet, but it will be soon :)

**Comment by Anth0rx** [comment]
> Not yet, but it will be soon :)

Great to hear. I am looking forward to it :)
