### ISSUE TITLE
Flying mode trap

### ISSUE THREAD

**Issue by donno2048** [minetest-LOTR/Lord-of-the-Test#166]
If you use flying enabled you can get **into** blocks with the same height as you (or higher), then, if you disable flying you will be trapped inside a block:

[zipped example of the problem](https://github.com/minetest-LOTR/Lord-of-the-Test/files/5350753/rec.zip)

**Comment by lumidify** [comment]
Hi (yes, I know it's been over two months),
I can't really see the problem in your video, probably because it cuts off too early. As far as I can tell, this isn't a real problem, though. Of course you can get yourself stuck if you can fly through solid material (with noclip). Did I misunderstand something here?

**Comment by neinwhal** [comment]
Sorry for late response, yeah this doesnt seem to be an issue. What you are describing with noclip, a minetest feature, to disable it, press H (unless you changed this key to something else)
Noclip causes you to clip through or "get into" blocks as you described.

Closing this issue as such, if it is however a separate issue, please clarify again and reopen the issue as necessary, thanks.
