### ISSUE TITLE
dualfurnace recipes don't appear in the book of craft

### ISSUE THREAD

**Issue by 3raven** [minetest-LOTR/Lord-of-the-Test#173]
Hi,

When i look in the book of crafts, recipes involving a dualfurnace (for example galvorn from lead and mese) dont appear, even if the craft is still possible. The problem is certainly in the guide code in the lottinventory mod.

Take care

**Comment by lumidify** [comment]
Hi,

Sorry it took so long to reply. I'm not entirely sure if those crafts should be in the regular guide - the dual furnace is meant to be special. Some of the crafting recipes are documented in the ring guide and miner handbook (`lottblocks:ring_guide` and `lottblocks:miner_handbook`), but I couldn't find galvorn there. I didn't write any of this code, though, so I'm not sure if this is just a mistake or if there was any rationale behind it. Maybe @Amaz1 knows more.

**Comment by Amaz1** [comment]
The only rationale behind it was that it was something that was meant to be done, but required extra work which I thought I'd do later.
Quite a few of the crafts should be there (e.g. bronze) but, because it uses a special type of crafting (https://github.com/minetest-LOTR/Lord-of-the-Test/blob/master/mods/lottblocks/crafting.lua#L31), detection for that would need to be added to the craft guide. Not something too complicated, but a bit time consuming.
Galvorn, on the other hand, would need to be added to the forbidden book of crafts, as that deals with all the galvorn crafts.

**Comment by neinwhal** [comment]
Fixed with 48015d3d4220830662b8262e09ea2d5fc618e836
