### ISSUE TITLE
Feature questions

### ISSUE THREAD

**Issue by epCode** [minetest-LOTR/Lord-of-the-Test#179]
So, hang with me, there's probably only a couple people reading this, but I'd like to get something straight. yes this has to do with Tolkien test. How come Tolkien test has a lot more features like some mobs and weapons and other various things, how come these in a much later version of the game do not have these?

Are you trying to keep it closer to a more realistic game.... or? This is not meant to be a complaint, take it as you like. I would like to help even seeing that this it mostly 5 feet down to being a resting game in development. but I would like to know if anyone would be willing to spare some time.

Thank you.

**Comment by lumidify** [comment]
Hi,
I assume with "Tolkien Test" you mean https://forum.minetest.net/viewtopic.php?f=15&t=20082, right? I had not actually heard of that before this post. Some of the features don't seem like they would be a very good fit for LOTT. Others may be good ideas, but considering that I hadn't even heard of Tolkien Test, there probably just wasn't anyone who wanted to get them into LOTT. As you yourself have noticed, LOTT isn't being developed very much anymore (mainly bug fixes so it keeps working on new versions of Minetest). A while ago, a complete rewrite was started (https://github.com/minetest-LOTR/Third-Age), but that isn't really playable yet and also very much lacks developers who have enough time to actually work on it.

Maybe @Amaz1 or @neinwhal has more comments on this matter.

**Comment by epCode** [comment]
I see and Understand. Thank you for your time.

**Comment by neinwhal** [comment]
About 3 years back; we announced the LOTT reached its "End of Development", there's a lot of reasons for it, but its best summarised in this post; https://forum.minetest.net/viewtopic.php?p=353875#p353875

Simply put, the base of LOTT we were working with, is too messy and incapable of supporting something bigger we had in mind, as such the current state of LOTT is simply in a repair state.
Tolkientest has since taken this base and added new additions to it, but it still doesn't change the fact that the base is messy and incapable and to take a further step forward, there needs to be a rewrite.

This is why LTTA exists: https://github.com/minetest-LOTR/Third-Age
Development has been entirely shifted in that direction, and because LOTT took years of building, coupled with the fact that the developers are all caught up in other real-life events, progress has been really slow.

**Comment by epCode** [comment]
Ah, I see. Thank you for your explanation.

**Comment by neinwhal** [comment]
Closing issue because i think all queries are addressed. If there are additional queries, feel free to reopen or look for any of us in the chat channels as stated on README
