### ISSUE TITLE
Guard Hiring Bug

### ISSUE THREAD

**Issue by lumidify** [minetest-LOTR/Lord-of-the-Test#54]
When a guard is hired and the amount of gold offered is more than 50, the game quits with the error `[...]lottmobs/init.lua:26: bad argument #2 to 'random' (interval is empty)`. As far as I know, the `random` function requires the smaller argument to come first and the larger argument to come second, so you should be able to fix this by using (for instance) `math.min` and `math.max` to put the arguments in the right order.
EDIT:
I could fix it for me with math.min and math.max, but on another computer, the problem never occurred, so I'm not sure what exactly causes the problem.

**Comment by Amaz1** [comment]
This is a very strange issue... In minetest, using //lua minetest.chat_send_all(math.random(10, 9)) worked, but in the lua shell, math.random(10, 9) threw an error... I wonder if it is something to do with windows being different to lua, or the version of lua bundled with Minetest being different from normal lua, or 32 bit vs 64bit... Weird!
Anyway, I've pushed a commit that a) hopefully fixes it and b) disables paying more than 50 gold for mobs, because that was worthless anyway, seeing as one would just be wasting gold, as math.random(1,1) == 1 will always be true!!
Hopefully this helps.
https://github.com/minetest-LOTR/Lord-of-the-Test/commit/0e5bf47236b7ce4c5c50481d8eaf6315410d0640
