### ISSUE TITLE
Use .mts instead of .we in lottmapgen.

### ISSUE THREAD

**Issue by pithydon** [minetest-LOTR/Lord-of-the-Test#58]
Moving to .mts would fix two issues, building spawning on your head and LOTT not working with mod security.

**Comment by Amaz1** [comment]
Not really possible for a couple of reasons:
1) meta isn't dealt with in .mts files, leading to some complication with nodes with formspecs, ect. Possible to deal with this with an abm, but this could cause more lag.. (Although some nodes might work with an on_rightclick function.)

2) .mts wouldn't, per se, fix buildings spawning on your head, as that would still need to be done via a node + amb, as terrain can be overwritten when placed as decorations, iirc. Also, getting the density right is a nightmare with register_decoration...

The mod security issue could probably be fixed by stripping down WE to just a function for placing schems, however...

**Comment by fishyWET** [comment]
Continuing on with what Amaz said, using mts wouldn't make the situation any much better. Hence, it is not much of an issue.
With regards to future developments on this issue. There is currently success with using voxelmanip to generate the buildings, which will remove the need for worldedit entirely. However, progress on this is slow as it is rather troublesome, so it seems unlikely the current situation will be improved anytime soon.
Closing issue, feel free to re-open if you would like to suggest a better method.
