### ISSUE TITLE
Potion brewer have incorrect cycled percent indication

### ISSUE THREAD

**Issue by amadin** [minetest-LOTR/Lord-of-the-Test#77]
Potion brewer show a brewing percents in looped cycle while cooking one potion, so you can see the brewing "100%" at last twice until cook one potion. 
Also if stone (for example) is in result slot then you still can activate Potion brewer and it will imitate cooking (change Potion brewer texture, formspec and show percent indicator in loop).

**Comment by lumidify** [comment]
Hi amadin,
The percentage represents how much of the currently burning fuel has been burnt up, not how much the recipe is done, so if you're using coal lumps and the potion needs multiple coal lumps, the percentage will go to 0% again when the next coal lump starts burning.
Could you clarify what you mean when you say that the result slot is "busy"?

**Comment by amadin** [comment]
> If you put stone in, does it just take your materials and then not give you the result you wanted because there is a stone in the result slot?
Yes but it imitate cooking but not cook, i write about this just in case.

**Comment by lumidify** [comment]
I think the problem is that the brewer doesn't check if the result slot is free when it starts cooking, so it just starts cooking, but then when it's done, it can't put the result into the result slot, so you never actually receive the potion you wanted. It should be possible to fix this, but I'll the other developers first.

**Comment by lumidify** [comment]
That is indeed weird behavior, I'll try to look into it.
